#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

cd cmd
. check-conf

bash prepare
bash gen-ssl
bash gen-file
bash gen-node "${control_plane_nodes[@]}"
bash dispatch "${control_plane_nodes[@]}"
bash wait-control-plane
bash gen-node "${worker_nodes[@]}"
bash dispatch "${worker_nodes[@]}"
bash wait-node "${worker_nodes[@]}"
