#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

. check-conf
cd ..

if [[ -z "$ssh_user" ]]; then
  ssh_user="$(id -u -n)"
fi
if [[ -z "$ssh_port" ]]; then
  ssh_port=22
fi

cmd=bash
if [[ "$ssh_user" != root ]]; then
  cmd="sudo -n $cmd"
fi

for i in "$@"; do
  tar -czf "$files_dir/k4s-$i.tgz" conf cmd -C "$k4s_dir" files/kubelet "nodes/$i"

  scp -P "$ssh_port" "$files_dir/k4s-$i.tgz" "$ssh_user@$i":/tmp
  ssh -p "$ssh_port" "$ssh_user@$i" \
    "rm -rf /tmp/k4s-$i && mkdir -p /tmp/k4s-$i && cd /tmp/k4s-$i && tar -xzf /tmp/k4s-$i.tgz && $cmd cmd/install-node $i"
done
