#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ $# -eq 0 ]]; then
  echo 'Usage: dispatch [install|reset|backup|upgrade] <ip>...'
  exit 1
fi

cmd=''
if [[ "$1" == install || "$1" == reset || "$1" == backup || "$1" == upgrade ]]; then
  cmd=$1
  shift
fi

. check-conf
cd ..

if [[ -z "$ssh_user" ]]; then
  ssh_user="$(id -u -n)"
fi
if [[ -z "$ssh_port" ]]; then
  ssh_port=22
fi

sb=bash
if [[ "$ssh_user" != root ]]; then
  sb="sudo -n $sb"
fi

mkdir -p "$files_dir"

for i in "$@"; do
  if [[ "$cmd" == reset || "$cmd" == backup ]]; then
    tar -czf "$files_dir/k4s-$i.tgz" conf cmd
  else
    tar -czf "$files_dir/k4s-$i.tgz" conf cmd -C "$k4s_dir" files/kubelet "nodes/$i"
  fi
  if [[ -n "$cmd" ]]; then
    scp -P "$ssh_port" "$files_dir/k4s-$i.tgz" "$ssh_user@$i":/tmp
    ssh -t -p "$ssh_port" "$ssh_user@$i" \
      "rm -rf /tmp/k4s-$i && mkdir -p /tmp/k4s-$i && cd /tmp/k4s-$i && tar -xzf /tmp/k4s-$i.tgz && $sb cmd/$cmd-node $i"
  fi
done
