#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

. check-conf
. "$files_dir/mo"

shopt -s expand_aliases
alias kubectl="'$files_dir/kubectl' --kubeconfig='$files_dir/admin.conf'"
. fn-ssl

mkdir -p "$files_dir"

gen_conf "$files_dir/admin.conf" admin "${control_plane_nodes[0]}:$apiserver_port"

f=calico.yaml
cat <"../tpl/$f" | mo >"$files_dir/$f"

f=kube-proxy.yaml
cat <"../tpl/$f" | mo >"$files_dir/$f"

f=coredns.yaml
cat <"../tpl/$f" | mo >"$files_dir/$f"

f=ingress-nginx.yaml
cat <"../tpl/$f" | mo >"$files_dir/$f"

if [[ -n "$nginx_example_domain" ]]; then
  f=nginx-example.yaml
  cat <"../tpl/$f" | mo >"$files_dir/$f"
fi

chmod 644 "$files_dir"/*.yaml
