#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

. check-conf

for i in "$@"; do
  if [[ " ${control_plane_nodes[@]} " =~ " $i " ]]; then
    bash gen-control-plane "$i"
  else
    bash gen-worker "$i"
  fi
done
