#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ $# -ne 1 ]]; then
  echo 'Usage: install-node <ip>'
  exit 1
fi
if [[ "$(id -u)" -ne 0 ]]; then
  echo 'Please run as root'
  exit
fi

. check-conf

node_ip="$(ip -o route get to "${control_plane_nodes[0]}" | sed -n 's/.*src \([0-9.]\+\).*/\1/p')"

if [[ "$1" != "$node_ip" ]]; then
  echo "Error: not local ip: $1"
  exit 1
fi

d="../nodes/$node_ip"
if [[ ! -e "$d" ]]; then
  echo "ERROR: $d not exist"
  exit 1
fi

if [[ -e /etc/kubernetes ]]; then
  echo "ERROR: /etc/kubernetes already exists"
  exit 1
fi
if [[ -e "$root_dir" ]]; then
  echo "ERROR: $root_dir already exists"
  exit 1
fi
if [[ " ${control_plane_nodes[@]} " =~ " $node_ip " && -e "$etcd_dir" ]]; then
  echo "ERROR: $etcd_dir already exists"
  exit 1
fi
if [[ -e /etc/systemd/system/kubelet.service ]]; then
  echo "ERROR: /etc/systemd/system/kubelet.service already exists"
  exit 1
fi
if [[ -e /etc/systemd/system/resolvconf.service ]]; then
  echo "ERROR: /etc/systemd/system/resolvconf.service already exists"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  echo 'ERROR: no docker'
  exit 1
fi
if ! command -v ipvsadm >/dev/null 2>&1; then
  echo 'ERROR: no ipvsadm'
  exit 1
fi

# TODO check port, swap...

install -v -C -m 755 -o root ../files/kubelet /usr/bin
(cd "$d" && cp -r --preserve=mode -- * /)

if [[ -f /etc/systemd/system/resolvconf.service ]]; then
  systemctl daemon-reload
  systemctl enable resolvconf
  systemctl start resolvconf
fi

systemctl daemon-reload
systemctl enable kubelet
systemctl start kubelet
