#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

. check-conf

mkdir -p "$files_dir"

for k in "${!files[@]}"; do
  f="$files_dir/$k"
  v="${files[$k]}"
  if [[ -f "$f" ]]; then
    : # TODO verify
  elif [[ "$v" == http://* || "$v" == https://* ]]; then
    echo "download $k: $v"
    curl -fsSL -o "$f" "$v"
  else
    echo "copy $k: $v"
    cp -f "$v" "$f"
  fi
done

install -v -C -m 755 -o root "$files_dir/kubectl" /usr/local/bin

# TODO offline images
