#!/usr/bin/env bash

# Copyright (c) 2021 CHEN Xianren. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

set -o errexit -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

. check-conf

shopt -s expand_aliases
alias kubectl="kubectl --kubeconfig='$files_dir/admin.conf'"
. fn-kube

wait_kubectl

for i in "$@"; do
  wait_node "$i"
  wait_node_net "$i"
  wait_node_ready "$i"
done
