apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address={{control_plane_ip}}
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        - --port=0
        - --secure-port={{scheduler_port}}
      image: {{images.scheduler}}
      imagePullPolicy: {{image_pull_policy}}
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: {{control_plane_ip}}
          path: /healthz
          port: {{scheduler_port}}
          scheme: HTTPS
        initialDelaySeconds: 15
        timeoutSeconds: 15
      name: kube-scheduler
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: conf
          readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
    - hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: File
      name: conf
