apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
    - command:
        - kube-controller-manager
        - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
        - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
        - --bind-address={{control_plane_ip}}
        - --client-ca-file=/etc/kubernetes/ssl/ca.pem
        - --cluster-name={{cluster_name}}
        - --cluster-signing-cert-file=/etc/kubernetes/ssl/ca.pem
        - --cluster-signing-key-file=/etc/kubernetes/ssl/ca-key.pem
        - --controllers=*,bootstrapsigner,tokencleaner
        - --kubeconfig=/etc/kubernetes/controller-manager.conf
        - --leader-elect=true
        - --port=0
        - --requestheader-client-ca-file=/etc/kubernetes/ssl/front-proxy-ca.pem
        - --root-ca-file=/etc/kubernetes/ssl/ca.pem
        - --secure-port={{controller_manager_port}}
        - --service-account-private-key-file=/etc/kubernetes/ssl/sa-key.pem
        - --use-service-account-credentials=true
      image: {{images.controller_manager}}
      imagePullPolicy: {{image_pull_policy}}
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: {{control_plane_ip}}
          path: /healthz
          port: {{controller_manager_port}}
          scheme: HTTPS
        initialDelaySeconds: 15
        timeoutSeconds: 15
      name: kube-controller-manager
      volumeMounts:
        - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
          name: flexvolume-dir
        - mountPath: /etc/kubernetes/ssl
          name: ssl
          readOnly: true
        - mountPath: /etc/kubernetes/controller-manager.conf
          name: conf
          readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
    - hostPath:
        path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
        type: DirectoryOrCreate
      name: flexvolume-dir
    - hostPath:
        path: /etc/kubernetes/ssl
        type: Directory
      name: ssl
    - hostPath:
        path: /etc/kubernetes/controller-manager.conf
        type: File
      name: conf
