#!/bin/bash

set -o errexit -o nounset -o pipefail

f=/etc/resolv.conf
if [[ ! -f "$f.k4s" ]]; then
  cp -f "$f" "$f.k4s"
fi

chattr -i "$f"
cat >"$f" <<EOF
# Generated by k4s. Do not edit.
options timeout:1
options attempts:3
{{#dns_servers}}
nameserver {{.}}
{{/dns_servers}}
EOF
chattr +i "$f"
cat "$f"

while true; do
  if dig >/dev/null 2>&1 +short "@{{cluster_dns}}" kubernetes.default.svc.{{service_domain}}; then
    break
  fi
  echo dig sleep 10s
  sleep 10
done

chattr -i "$f"
cat >"$f" <<EOF
# Generated by k4s. Do not edit.
options timeout:1
options attempts:3
search default.svc.{{service_domain}} svc.{{service_domain}} {{service_domain}}
nameserver {{cluster_dns}}
EOF
chattr +i "$f"
cat "$f"
